# Máquina que vai executar o script gerado pelo rancher para instalar o kubernetes
---
- name: Download e instala Docker
  shell: curl https://releases.rancher.com/install-docker/20.10.sh | sh
  args:
    creates: /usr/bin/docker

- name: Adiciona usuário ubuntu ao grupo docker
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Garante que o Docker está rodando
  service:
    name: docker
    state: started
    enabled: yes
